# `numpy

- core packages for numerical computing in Python 
- many packages are built on topy numpy
- optimized for processing: faster due to memory access

In [4]:
# import Numpy with standard abbreviation 
import numpy as np

# Variables

We can think about variables as a name we assign tp a partocular object in Python.

For example...

In [5]:
# assign a small array to a variable 'a'

a = np.array( [ [1, 1, 2], [3, 5, 8] ] )

When we run the cell, we store the variable and its value. 

Can see it in 2 ways:

In [6]:
# way number 1: enter just the variable name
a

array([[1, 1, 2],
       [3, 5, 8]])

In [7]:
# way 2: use print ()
print(a)

[[1 1 2]
 [3 5 8]]


## Naming variables 

We are going to use `snake_case` for naming variables.

## Variables and objects

**object**: encountered in Python documentation and tutorials. 

Can be thought of as... a bundle of properties and actions about something specific

Example: 
- object: data frame
- propoerties: number of rows; names of columns; data created
- actions: selecting a row, adding a column 

A **variable** is a name we give a specific object, and the same object can be referenced by different variables. 

Example:
- The Sun (star at center of solar system) = Object
- sol = spanish word for Sun = Variable
- soleil = Sun in french = another Variable


In practice, use the object and variable interchangeably :)

# Types 

Each object in Python has a type. 

**type** = what kind of object it is 
- can also call it the **class** of the object

We can see the type/class of object by using teh `type` function:

In [10]:
print(a)

# will return the type is an np.array
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in the NumPy package. 

We can check the type of an entry in the array by indexing: 

In [13]:
# want to access the first element of the first row
print(a[0][0])

type(a[0][0])

1


numpy.int64

In [17]:
# access the number 5 in the array a
print(a[1][1])

# or

print(a[1, 1])

5
5


# Functions 

`print` was our example of Python function!

A **function**:
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **outputs**

argument = parameter
- you might see argument more often in documentation

Ask information about a function by executing `?` follwed by function name:



In [18]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in parenthesis 
- then a short description about what function does 
- list of arguments and a brief explanation

Different types of arguments inside the parenthesis:

- **non-optional arguments**: arguments you need to sepcify for the function to do something 
- **optional arguments**: arguments that are pre-filled with a default value in the function; but can be overwritten 

`optional argument = default_value`

In [19]:
print('changing the default end argument of the print function', end = ':)')

changing the default end argument of the print function:)

# Attributes and Methods

An object in Python has attributes and methods.

- **attribute**: a property of an object, a piece o info about it.  
- **method**: a procedure associated with an object. an action where main ingredient is the object itself. Things your object does.

- Example: object = cat
    - attributes: name, color, age, weight
    - method: meow(), nap()
- Example: object = fish
    - attribute: weight, scale_color, species
    - method: swim(), eat(), jump()

Access a variables attributes and methods by adding a period `.` at the end of the variable's name.

`variable.variable_method()` 

or

`variable.variable_attribute`

Examples: 

Methods and attributes of NumPy arrays:

In [1]:
import numpy as np

In [3]:
# define a 3x3 array
var = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
var

In [4]:
# shape: attribute telling us # of elements in each dimension of the array
var.shape

In [5]:
type(var.shape)

In [7]:
# ndim is a n attribute holding the number of array dimensions
var.ndim

In [ ]:
type(var.ndim)

Notice that attributes can have many different data types.

Examples of methods:

In [9]:
# min method for array
# return minimum value in the array
var.min()

In [12]:
type(var.min)

# R & Python

Python:
`var.min()`

R:
- doesn't use meethods within an object
- functions in R are extrinsic to (outside of) the objects they are acting on 

        Example: recreate getting min value in an array
        
            - in R there would be 2 separate items
            
            ```
            # this is R code
            var <- array(c(1, 4, 7, 2, 5, 8, 3, 6, 9)), dim = c(3, 3)
            min(var)
            ```
- Using pipe operator >%> in R tidyverse is closer to the `.` in Python. It is passing `var` to the `min()` function

            # this is R code
            var <- array(c(1, 4, 7, 2, 5, 8, 3, 6, 9)), dim = c(3, 3)
            var >%> min()
            ```